-- MySQL Script generated by MySQL Workbench
-- Thu Nov 10 18:01:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Books
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Books
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Books` DEFAULT CHARACTER SET utf8 ;
USE `Books` ;

-- -----------------------------------------------------
-- Table `Books`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Books`.`users` (
  `users_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (`users_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Books`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Books`.`authors` (
  `authors_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`authors_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Books`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Books`.`books` (
  `books_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `authors_authors_id` INT NOT NULL,
  PRIMARY KEY (`books_id`),
  INDEX `fk_books_authors1_idx` (`authors_authors_id` ASC) VISIBLE,
  CONSTRAINT `fk_books_authors1`
    FOREIGN KEY (`authors_authors_id`)
    REFERENCES `Books`.`authors` (`authors_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Books`.`users_has_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Books`.`users_has_books` (
  `users_users_id` INT NOT NULL,
  `books_books_id` INT NOT NULL,
  INDEX `fk_users_has_books_books1_idx` (`books_books_id` ASC) VISIBLE,
  INDEX `fk_users_has_books_users_idx` (`users_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_books_users`
    FOREIGN KEY (`users_users_id`)
    REFERENCES `Books`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_books_books1`
    FOREIGN KEY (`books_books_id`)
    REFERENCES `Books`.`books` (`books_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Books`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Books`.`favorites` (
  `books_books_id` INT NOT NULL,
  `users_users_id` INT NOT NULL,
  INDEX `fk_favorites_books1_idx` (`books_books_id` ASC) VISIBLE,
  INDEX `fk_favorites_users1_idx` (`users_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_favorites_books1`
    FOREIGN KEY (`books_books_id`)
    REFERENCES `Books`.`books` (`books_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorites_users1`
    FOREIGN KEY (`users_users_id`)
    REFERENCES `Books`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
